### ISSUE TITLE
Updating your hsg-project system to use this repository

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/administrative-timeline#1]
@HistoryAtState/editors: If you had cloned an earlier edition of this resource from our private repository (perhaps only @tomfaith?), please perform the following step to delete the old edition, then proceed to the next steps to add the resource:

1. In oXygen's project pane, right-click on `repos/administrative-timeline` and select Delete.  

If you not had this resource on your computer (everyone else), please add them to your hsg-project using the following steps:

1. In oXygen's External Commands menu, select "Fetch updates for all repositories"
2. When you see BUILD SUCCESSFUL, click in the Project pane and, when asked if you want to reload hsg-project.xpr, select Reload
3. In oXygen's External Commands menu, select "1. Clone all repositories." 
4. When you see BUILD SUCCESSFUL, repeat step 3 once more.
5. You now have administrative-timeline. To confirm, right-click on the `repos` folder in the Project pane and select Refresh. You will now see administrative-timeline.

**Comment by joewiz** [comment]
I just pushed the commits with the necessary changes to hsg-project, so if you already did the steps above in the last 6 minutes, please repeat them. Let me know if you have any questions.

**Comment by KerryHite** [comment]
Joe,
Great instructions. It worked!

Kerry

p.s. I also followed the instructions you sent for Secretary Pompeo.  I
followed directions. I'm not sure what end result I was trying to get so I
don't know where to look to see if it worked, but I will assume all is good.

**Comment by joewiz** [comment]
Thanks for letting me know, Kerry! I'm so glad the instructions worked!
